### ISSUE TITLE
Custom toast views will not be supported starting from API 30

### ISSUE THREAD

**Issue by karimelbahi** [TalhaFaki/ComposableSweetToast#10]
Hi, As mentioned in google Docs custom toast views will not be supported starting from API 30!

https://developer.android.com/reference/android/widget/Toast#setView(android.view.View):~:text=setView%20(View%20view)-,This%20method%20was%20deprecated%20in%20API%20level%2030.,-Custom%20toast%20views

**Comment by tfaki** [comment]
> As mentioned in google Docs custom toast views will not be supported starting from API 30!
> 
> 
> 
> 
> 
> https://developer.android.com/reference/android/widget/Toast#setView(android.view.View):~:text=setView%20(View%20view)-,This%20method%20was%20deprecated%20in%20API%20level%2030.,-Custom%20toast%20views

Hi, i know that. I will replace to snackbar
